CREATE TABLE `log4net` (
    `Id` INT(11) NOT NULL AUTO_INCREMENT,
    `LogTime` DATETIME DEFAULT NULL,
    `Thread` VARCHAR(255) DEFAULT NULL,
    `Level` VARCHAR(255) DEFAULT NULL,
    `Logger` VARCHAR(255) DEFAULT NULL,
    `Message` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`Id`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;